name: Build OT Server

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake \
            liblua5.2-dev libsqlite3-dev \
            libcrypto++-dev libpugixml-dev \
            libboost-system-dev libboost-filesystem-dev libboost-iostreams-dev

      - name: Configure with CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Compile
        run: |
          cd build
          make -j$(nproc)

      - name: Upload server binary
        uses: actions/upload-artifact@v4
        with:
          name: otserver-executable
          path: build/theforgottenserver

      - name: Upload client binary (if built)
        uses: actions/upload-artifact@v4
        with:
          name: otclient-executable
          path: SabrehavenOTClient/build/otclient

